<a href="https://colab.research.google.com/github/bekkahmoore/Numerical-Methods/blob/main/Project4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Project 4**
 
 **Sanjiv T, Kushal K, Aayush K, Bekkah M**

**Numerical Methods --> Dr. Jacob** 




#Gauss-Jordan Method
This method helps us to solve the linear equations. 
This is in the form as shown below:

\begin{align}
a_{1,1} x_1 +&amp;\dots a_{1,n} x_n = y_1\\
&amp;\vdots\\
a_{n,1}x_1+&amp;\dots a_{n,n} x_n = y_n
\end{align}


We will solve the equation by putting the above equation in the form shown as below:


\begin{array}{ccc|c}
a_{1,1} &amp; \dots &amp; a_{1,n} &amp; y_1\\
\vdots&amp;\ddots&amp;\vdots&amp;\vdots\\
a_{n,1} &amp;\dots&amp; a_{n,n}&amp;y_n
\end{array}

This is called augmented matrix form. And we will futher solve this problem.**bold text**

In [ ]:
import math
import numpy as np

We need to swap the rows during the operation, the python code for the swapping is :

In [ ]:
def swapping_Rows(M,R1,R2): 
  newMatrix = []
  for i in range(len(M)):
    if i == R1:
      newMatrix.append(M[R2,:])
    elif i == R2:
      newMatrix.append(M[R1,:])
    else:
      newMatrix.append(M[i,:])
  return np.array(newMatrix)

Now, checking whether my code works or does not for swapping rows.

In [ ]:
swapping_Rows(A,0,1)

array([[20,  5,  8],
       [ 8,  7,  6]])

We need to add the rows during the operation, the python code for the adding is :

In [ ]:
def adding_row(M,select_Row, modifierRow, V):
  new_Row = M[select_Row,:]+V*M[modifierRow,:]
  newMatrix = []
  for i in range(len(M)):
    if i != select_Row:
      newMatrix.append(M[i,:])
    else:
      newMatrix.append(new_Row)
  return np.array(newMatrix)

Now, checking whether my code works or does not work for adding rows.

In [ ]:
adding_row(A,2,0,10)

We need to multiply the rows and column during the operation, the python code for the multiplication is :

In [ ]:
def Multiplying(M,row,constant):
  newMatrix =[]
  for i in range(len(M)):
    if i != row:
      newMatrix.append(M[i,:])
    else:
      newMatrix.append(1/M[row,constant]*M[row,:])
  return np.array(newMatrix)
  

Now, checking whether my code works or not for multipying.

In [ ]:
Multiplying(A,0,2)


array([[ 1.33333333,  1.16666667,  1.        ],
       [20.        ,  5.        ,  8.        ]])

We will use the Gauss Jordan Method here. The python code for Gauss Jordan is :

In [ ]:
def gaussJordan(M):
  newMatrix = M
  for pivot in range(len(M)):
    newMatrix = Multiplying(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = adding_row(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(M)):
      newMatrix = adding_row(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix

Creating a list of elements with A.

In [ ]:
A = np.array([[8,7,6],[20,5,8]])
A


array([[ 8,  7,  6],
       [20,  5,  8]])

Implementing the code for Gauss Jordan Method for the array of elements A'

In [ ]:
gaussJordan(A)


array([[ 1.  ,  0.  ,  0.26],
       [-0.  ,  1.  ,  0.56]])

Creating the list of array of elements named B using python code.

In [ ]:
B = np.array([[8,7,6],[20,5,8,4]])
B

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([8, 7, 6]), list([20, 5, 8, 4])], dtype=object)

So,what happened here was, the number of rows and columns in  list was different with each other.

In [ ]:
import numpy as np
 
 # userdefined function
def gaussElimin(a,b):
  n = len(b)
  # Elimination Phase
  for k in range(0,n-1):
    for i in range(k+1,n):
      if a[i,k]  != 0.0:
        lam = a [i,k]/a[k,k]
        a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
        b[i] = b[i] - lam*b[k]
        #back subsitution
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
  return b

For guass elimination method we took 3 equation 4x1-2y1+z=11 -2x2+4y2-2z=-16 X3-2y2+4z=17





In [ ]:
# Encode A and b
A = np.array([[ 4.0, -2.0, 1.0], [-2.0, 4.0, -2.0], [1.0, -2.0, 4.0]])
b = np.array([11.0, -16.0, 17.0])
print(A)
print(b)

[[ 4. -2.  1.]
 [-2.  4. -2.]
 [ 1. -2.  4.]]
[ 11. -16.  17.]


In [ ]:
# Using gauss Elimination
gaussElimin(A,b)

array([ 1., -2.,  3.])

Now, working on with three rows N columns to find the gauss Jordan value..

In [ ]:
C = np.array([[1,12,3,4],[21,3,4,5],[3,-4,51,6]])
C

array([[ 1, 12,  3,  4],
       [21,  3,  4,  5],
       [ 3, -4, 51,  6]])

In [ ]:
gaussJordan(C)

array([[ 1.00000000e+00,  1.79797579e-15,  0.00000000e+00,
         1.72413793e-01],
       [-0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         2.86472149e-01],
       [ 0.00000000e+00, -1.38028664e-16,  1.00000000e+00,
         1.29973475e-01]])

Looks like we have successfully run the code now.But we are still confused the values we got after running the code is right or wrong.
 In this way,the system of linear equations can be solved,in which the given system operations solution can be obtained by Elimination phase and back subsitution.